# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pubsub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\x12\x06pubsub\"1\n\x17PublisherConnectRequest\x12\x16\n\x0epublisher_name\x18\x01 \x01(\t\"*\n\x18PublisherConnectResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\";\n\x12\x43reateTopicRequest\x12\x16\n\x0epublisher_name\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"7\n\x13\x43reateTopicResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"O\n\x15PublishMessageRequest\x12\x16\n\x0epublisher_name\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\":\n\x16PublishMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x18SubscriberConnectRequest\x12\x17\n\x0fsubscriber_name\x18\x01 \x01(\t\"V\n\x19SubscriberConnectResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12)\n\x10offline_messages\x18\x02 \x03(\x0b\x32\x0f.pubsub.Message\"A\n\x17SubscribeToTopicRequest\x12\x17\n\x0fsubscriber_name\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"<\n\x18SubscribeToTopicResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf8\x03\n\rBrokerService\x12U\n\x10\x43onnectPublisher\x12\x1f.pubsub.PublisherConnectRequest\x1a .pubsub.PublisherConnectResponse\x12\x46\n\x0b\x43reateTopic\x12\x1a.pubsub.CreateTopicRequest\x1a\x1b.pubsub.CreateTopicResponse\x12O\n\x0ePublishMessage\x12\x1d.pubsub.PublishMessageRequest\x1a\x1e.pubsub.PublishMessageResponse\x12X\n\x11\x43onnectSubscriber\x12 .pubsub.SubscriberConnectRequest\x1a!.pubsub.SubscriberConnectResponse\x12U\n\x10SubscribeToTopic\x12\x1f.pubsub.SubscribeToTopicRequest\x1a .pubsub.SubscribeToTopicResponse\x12\x46\n\x0fReceiveMessages\x12 .pubsub.SubscriberConnectRequest\x1a\x0f.pubsub.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHERCONNECTREQUEST']._serialized_start=24
  _globals['_PUBLISHERCONNECTREQUEST']._serialized_end=73
  _globals['_PUBLISHERCONNECTRESPONSE']._serialized_start=75
  _globals['_PUBLISHERCONNECTRESPONSE']._serialized_end=117
  _globals['_CREATETOPICREQUEST']._serialized_start=119
  _globals['_CREATETOPICREQUEST']._serialized_end=178
  _globals['_CREATETOPICRESPONSE']._serialized_start=180
  _globals['_CREATETOPICRESPONSE']._serialized_end=235
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_start=237
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_end=316
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_start=318
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_end=376
  _globals['_SUBSCRIBERCONNECTREQUEST']._serialized_start=378
  _globals['_SUBSCRIBERCONNECTREQUEST']._serialized_end=429
  _globals['_SUBSCRIBERCONNECTRESPONSE']._serialized_start=431
  _globals['_SUBSCRIBERCONNECTRESPONSE']._serialized_end=517
  _globals['_SUBSCRIBETOTOPICREQUEST']._serialized_start=519
  _globals['_SUBSCRIBETOTOPICREQUEST']._serialized_end=584
  _globals['_SUBSCRIBETOTOPICRESPONSE']._serialized_start=586
  _globals['_SUBSCRIBETOTOPICRESPONSE']._serialized_end=646
  _globals['_MESSAGE']._serialized_start=648
  _globals['_MESSAGE']._serialized_end=689
  _globals['_BROKERSERVICE']._serialized_start=692
  _globals['_BROKERSERVICE']._serialized_end=1196
# @@protoc_insertion_point(module_scope)
